### ISSUE TITLE
Dask User Survey

### ISSUE THREAD

**Issue by mrocklin** [dask/community#148]
Historically we've timed the annual Dask user survey to be around the SciPy Conference.  Do we want to shift that to be a bit earlier this year and instead orient it around the Dask User Summit?

cc @TomAugspurger

**Comment by TomAugspurger** [comment]
Makes sense! Maybe we target May 5th or 12th to have the form up, so that
we can promote it during the conference.

**Comment by TomAugspurger** [comment]
@mrocklin do you have access to the Google form we used for the previous rounds? I think my access was under my anaconda.com gmail account.

---

To anyone, let me know if you're interested in tweaking / adding / removing questions from the previous year's survey. We just need to keep in mind that

1. Changing a question's wording makes it harder to compare to previous years
2. The survey shouldn't grow too long.

**Comment by mrocklin** [comment]
Done

**Comment by jacobtomlinson** [comment]
During the Dask Community meeting we had an idea generation session for potential questions. Here's a list from the [meeting notes](https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit#). I encourage folks to add more ideas here if they have them.

- Prometheus style monitoring
- Who has problems with Parquet . what file formats do you use.  Hive.
- IO usability / Auth / Tokens
- What cluster managers do people use?  Dask-cloudprovider?  Dask-ssh?  For-profit companies?  Roll your own?
- Where do people get their data from?  Generated from some other process?  Coming from a database?  Sure, you use Parquet, but did Dask make that?  If so, - where did the raw data come from?
- Is Dask stable enough?  
  - API stability and runtime stability
- How long have you been using Dask?  Beginner or Advanced?
- Release frequency
  - Too frequently, not frequently enough?
  - LTS versions?
- Industry
- Are you satisfied with API compatibility with in-core libraries
- What functionality is missing?  
- Support quality / issue responsiveness
- Top three blocking dask issues
- Security, switched to TLS on by default now in cloudprovider.  Is this a desirable thing?  
- Where are users communicating with us?  Gitter, Github, StackOverflow, Github Discussions, Twitter
- Dashboarding
  - Do you know about performance reports and do you use them?
  - What plots are most useful?
  - “How do you diagnose and debug performance, …”
- How many people manage their own deployments vs how many people are being supported by someone else within their org
- How many people use futures / delayed vs dataframes / arrays
- Are people satisfied with the API surface that we’re showing.  For example should the scheduler be more or less transparent?  Are the methods that we have - on the Client more or less.
- Is anyone interested in enhancement proposals?
- Do people use the dask-dev docker image?  Directly?  Base off of them?  Do you want more varied options?
- What are your top two most common pain points?  (free form answer)
- Do you want to run multiple jobs at once on the same cluster?  Fair scheduling among different update_graph calls.
- In what configurations do people want to use different hardware?  Heterogeneity?
- Data size distribution. GB, TB, PB
- How inviting / engaged are maintainers with you?  How welcoming is the community?  “If you found a bug in Dask would you feel comfortable contributing a - fix?”
- How understandable do you find Dask internals?  How leaky are our abstractions?  As you explore internals how easy are things to understand? 
- How easy is it to use Dask?
- How do you find Dask’s Documentation quality?  Do you ever look at the source because the documentation doesn’t give you what you need?
- For how long have you been writing Python?  Dask?  Programming in general?
- How easy is it to contribute?
  - Contributor guidelines
  - Employer support
  - Welcoming community
- What stops you from raising an issue?  Is your employer understanding?
- How are the Dask training materials?  Do you need something more advanced? Do people even know about them?

**Comment by jakirkham** [comment]
Thanks Tom and Jacob 🙂

It looks like these two may be duplicates (or perhaps the latter one is just emphasizing the former one is free-form)?

> * Added "How else can Dask improve"
> ...
> * Added a free-form "How can Dask improve" question.

**Comment by GenevieveBuckley** [comment]
@jakirkham - I clicked through the survey and there don't appear to be any duplicate questions. I think it just appears twice in Tom's list above.

> How often do you use Dask?
>
> a) Just looking for now
> b) Occasionally
> c) Every day
> d) I use Dask all the time, even when I sleep

It seems like there's a big gap between "occasionally" and "every day". In addition, "occasionally" is ambiguous & will mean different things to different people. Finer grained options for answers in this range would help.

d) is funny, but doesn't yield a lot of valuable information compared with c). People will click on it if they think it's funny, possibly regardless of their actual use.

**Comment by TomAugspurger** [comment]
Thanks for the feedback!

> It seems like there's a big gap between "occasionally" and "every day". In addition, "occasionally" is ambiguous & will mean different things to different people. Finer grained options for answers in this range would help.

I agreed on both all your points. However, this is a question that's been present since 2019, so I'm tempted to leave it in place so that we can compare results with earlier years. Do you have thoughts on what's more valuable: clarifying the question vs. preserving comparability to previous years? (I'm struck by the similarity to API design here. Changing a question's wording is like an API breaking change 😄)

> This feedback seems difficult to act on, unless you also know which field they're in.

Yes, it'd be good to capture that somehow. I'll look to see if the Python or StackOverflow surveys have a question about "industry / field" so that we have a list of industries to choose from.

> we could probably modify the "Other: ____" answer option to something like "More examples in my field (write your field here): ______"

One challenge here: that question is currently a multiple-choice (select one) rather than a checkbox. So we can't easily have an "other" field where they fill in that information. But if we capture their industry in a separate question, we'll hopefully get what we need.

**Comment by GenevieveBuckley** [comment]
> I agreed on both all your points. However, this is a question that's been present since 2019, so I'm tempted to leave it in place so that we can compare results with earlier years. Do you have thoughts on what's more valuable: clarifying the question vs. preserving comparability to previous years? (I'm struck by the similarity to API design here. Changing a question's wording is like an API breaking change smile)

Oh ok, your comment above made it sound as though this was a new question added in 2021.

Yeah, that does make things trickier. I guess it depends on what'll be more important in future years: being able to compare backwards to 2019 & 2020, or having a finer grained view.

**Comment by TomAugspurger** [comment]
To help with the issue Genevieve identified about "This feedback seems difficult to act on, unless you also know which field they're in", I added a question: "What industry do you work in?" Currently the options are


* Accounting / Finance / Insurance
* Medicine / Health
* Manufacturing
* Logistics / Transportation
* Geoscience
* Life sciences
* Social science
* Astronomy
* Physics
* Other…

Let me know if you want anything added / removed / split apart in that list.

---

I think this is essentially ready to go. I recommend that we promote the survey at the start of the social sessions, and have all the workshop organizers promote it too. We could maybe slip it in at the start of the keynotes if there are other things to share then, but I don't want to take too much time.

**Comment by martindurant** [comment]
Would add marketing

**Comment by TomAugspurger** [comment]
@fjetter I added a question "Is Dask resilient enough for you? (e.g. computations complete)." that hopes to track the issue you cared about. Do you think that wording captures what you wanted? Any better way to phrase it? The "computations complete" wording isn't perfect, since things can fail for issues in the user code, but we're trying to capture issues in Dask's "runtime". I also added "Improve Resiliency" to the options in "What common feature requests do you care about most?"

**Comment by GenevieveBuckley** [comment]
Now that the Dask User Survey is being promoted to attendees at the Dask Summit, should we also have a post on the dask blog to promote it too?

I'm happy to organise a draft for that if you'd like - I'm about to spend a bit of time over on blog stuff anyway.

**Comment by jrbourbeau** [comment]
Have we tweeted from the Dask account about the survey yet? That's also a good way to promote the survey to users

**Comment by GenevieveBuckley** [comment]
> Have we tweeted from the Dask account about the survey yet? That's also a good way to promote the survey to users

...I was just about to leave a comment with this too! I don't think so, I'll schedule something in tweetdeck to go out on Monday morning US time (uh, if I don't get too confused calculating the time difference, that is)

**Comment by GenevieveBuckley** [comment]
Tweet scheduled. It should go out around 9am Monday PDT. The text says:
> The Dask User Survey is out again! Tell us how you use Dask, and help us make it better for everyone:
https://docs.google.com/forms/d/e/1FAIpQLSfio2RIQGIQsX1QTJh4JXmTFK8s-7BbsR0VnfmsWXu1Ccb2Yw/viewform

**Comment by GenevieveBuckley** [comment]
Blogpost draft made, see here: https://github.com/dask/dask-blog/pull/97

**Comment by TomAugspurger** [comment]
Thanks for handling the promotion @GenevieveBuckley. If you want, last year we added it to a couple more places:

1. The root of the dask docs: https://github.com/dask/dask/pull/6328/files
2. dask.org homepage: https://github.com/dask/dask.github.io/pull/27/files

**Comment by GenevieveBuckley** [comment]
1. The root of the dask docs - PR made here https://github.com/dask/dask/pull/7694
2. dask.org homepage - PR made here https://github.com/dask/dask.github.io/pull/48

I don't have merge access to either of these repositories, but I'm sure someone who does will be along soon.

**Comment by GenevieveBuckley** [comment]
The 2021 Dask user survey has closed, and the survey results are available here: https://blog.dask.org/2021/09/15/user-survey
