### ISSUE TITLE
Codecov Bash Uploader Security Notice

### ISSUE THREAD

**Issue by andersy005** [dask/community#149]
As some of you may already know, codecov recently announced that earlier this month someone exploited a security hole in their bash uploader ([full security notice](https://about.codecov.io/security-update/?utm_medium=email&utm_source=marketo&ajs_uid=2706148&ajs_event=Clicked%20Email&mkt_tok=MzMyLUxWWC03NDEAAAF8dJt92r2YvZzABLaHORcUB8ZJPAHDeacNRPMPqyfqPvUpQiNV3LCzx4NhqX7lWhTJIcpRamFVZZYNiR3EEPXpFbOBZQ6BZAcPJQcCwexX)) which may have resulted in the theft of private tokens/secrets used in CI services. 

> Every repository that uses the Codecov Bash Uploader to upload code coverage results to Codecov.io should reroll all of their security tokens, as they may have been stolen from a hack to the utility.

Just thought I'd bring this to folks' attention in case there are repos in the dask org that uses GitHub action secrets and are affected by this notice.

**Comment by andersy005** [comment]
cc @dask/maintenance

**Comment by fjetter** [comment]
Thanks for pinging @andersy005 

According to codevoc there are a few of our repos registered with them

Active in use
- [ ] dask-mpi
- [ ] dask

About to be set up / first branches running
- [ ] dask-distributed

Not using it for the past year, so probably safe
- [ ] dask-ml


I haven't checked, yet, if there are even any secrets to leak since I do not have admin access to these repos.

**Comment by jrbourbeau** [comment]
Yeah, thanks for bringing this up @andersy005. I looked though all the repos @fjetter mentioned and none of them have repository-level secrets.

There is an Dask organization-level `ORG_GITHUB_TOKEN` secret (last updated on Jul 22, 2020). It looks like this token is used over in `dask/.github` for [syncing labels across repositories](https://github.com/dask/.github/blob/a9568fe4b050eee100f0cc1e15c8a6d8ed13c71d/.github/workflows/labels.yml). @jacobtomlinson would you mind updating the `ORG_GITHUB_TOKEN` secret or is it okay if I temporarily remove it (it's been two months since we last ran the [workflow which uses this secret](https://github.com/dask/.github/actions/workflows/labels.yml))?

**Comment by jrbourbeau** [comment]
@jacobtomlinson as a heads up, I've gone ahead and temporarily removed the `ORG_GITHUB_TOKEN` org-level secret (I don't think this will impact many workflows today)

**Comment by jrbourbeau** [comment]
Closing this issue as we've wiped all GitHub secrets for repos which were using codecov. Thanks again for flagging this @andersy005

**Comment by andersy005** [comment]
> Thanks again for flagging this @andersy005

Of course!
