### ISSUE TITLE
Off-cycle release this Friday

### ISSUE THREAD

**Issue by mrocklin** [dask/community#177]
This came up in the maintenance meeting.  Do we want to perform an off-cycle release this Friday? (we would normally release next Friday). 

The motivation would be https://github.com/dask/dask/pull/8040 , which resolves current bad behavior of the local scheduler in not optimizing for low memory use.  This is, I think, a critical bug fix.  However the critical bug has also been around since April.

**Comment by jrbourbeau** [comment]
Thanks for raising this issue @mrocklin. I'm fine with releasing this Friday to get that fix out. That issue seems like it's impacted lots of users.

I also wanted to flag https://github.com/dask/dask/pull/8055 which we should merge before releasing (to avoid an `ImportError` when using Dask Arrays) 

cc @quasiben @jakirkham @jsignell

**Comment by jakirkham** [comment]
Both of those have been merged. Have asked around to see if there's anything else we needed to fix and didn't hear anything. So I think we are good to go

**Comment by jrbourbeau** [comment]
Great, thank @jakirkham! I also want to get https://github.com/dask/distributed/pull/5239 in (which is a small tweak on some new, yet-unrelated dashboard plots). I'll plan to merge that in and start pushing out the release in ~1 hour

**Comment by jrbourbeau** [comment]
Alright, pushing this out...

**Comment by jrbourbeau** [comment]
Closing as 2021.8.1 is out. Thanks all!

**Comment by jakirkham** [comment]
Thanks James! 😀
