### ISSUE TITLE
Bugfix release

### ISSUE THREAD

**Issue by mrocklin** [dask/community#241]
We introduced a slight regression.  It's fixed in https://github.com/dask/distributed/pull/6256 .  Do we want to release `2022.04.3` tomorrow?  Historically I would do this if anything came up on the weekend following release, in hopes that we don't affect that many people once the week gets going.  

The bug is that if someone is including `Client(processes=False)` in a script, that script will not terminate cleanly.  It's not a super-critial issue, but if releases are still very cheap then I think it makes sense to push one out.  cc @jrbourbeau

**Comment by jrbourbeau** [comment]
Thanks for fixing that issue @mrocklin. Happy to push a bugfix release out today (releases are still cheap). It doesn't look like we've merged anything particularly controversial that we'd want to let simmer in `main` since the last release. I'll plan to push 2022.05.0 out in a couple of hours if no further comments

cc @quasiben @jakirkham @jsignell @fjetter for visibility

**Comment by quasiben** [comment]
no blockers on our end

**Comment by jrbourbeau** [comment]
Pushing things out now...

**Comment by jrbourbeau** [comment]
2022.05.0 is on PyPI and conda-forge PRs are open
