### ISSUE TITLE
Dask.org is down

### ISSUE THREAD

**Issue by quasiben** [dask/community#274]
Cloudflare is reporting an SSL failure for [dask.org](https://www.dask.org/)

<img width="938" alt="Screen Shot 2022-09-06 at 10 21 13 AM" src="https://user-images.githubusercontent.com/1403768/188659870-292d2510-e4bd-4db4-8404-985071930c90.png">

We are actively investigating

**Comment by quasiben** [comment]
Dask.org is up now for me.  @jacobtomlinson and I disabled and cleared the cache on cloudflare which seems to have resolved the 525 issue.  If there are any outages today please reopen

**Comment by jrbourbeau** [comment]
Thanks for handling this @quasiben @jacobtomlinson!

**Comment by mrocklin** [comment]
Indeed, many thanks

**Comment by jacobtomlinson** [comment]
Here's a quick postmortem of what happened. We plan to meet later this week to go into more depth here.

### Context
- When we launched the rebrand of the dask.org website we switched over to [Webflow](https://webflow.com/) for hosting.
- Our domain name is managed by NumFOCUS who gives maintainers access via [CloudFlare](https://www.cloudflare.com/en-gb/) which allows us to set up our DNS rules and also leverage some caching, page rules and DDOS protection.
- When we switched from Readthedocs to Webflow we updated the dask.org domain to point to `proxy-ssl.webflow.com` as instructed by the Webflow setup guide.
- We also enabled the caching proxy in Cloudflare at this time to limit how much bandwidth Webflow would charge us for.
- The WebFlow SSL proxy uses LetsEncrypt to generate certificates. A certificate was generated between the time we update the DNS and enabled the caching.

### Incident
- A user [reported to us via Slack](https://dask.slack.com/archives/C019Q0QSD4J/p1662472863302359) that dask.org was down.
- It appeared that Cloudflare was unable to access Webflow. Investigation began.
- It turned out that the certificate that Webflow was using had expired and because Cloudflare caching was enabled [Webflow was unable to generate a new certificate](https://discourse.webflow.com/t/error-525-ssl-handshake-failed/73756) resulting in Webflow being unable to securely send traffic.
- To remediate we disabled and purged the Cloudflare cache which allowed Webflow to generate a new certificate and begin serving requests again.

### Follow-up tasks
- Maintainers should be notified of outages like this automatically rather than relying on user feedback. We will investigate some monitoring.
- It appears we could change the DNS rules to point to `proxy.webflow.com` instead and enable the caching again which would give us the bandwidth savings and DDOS protection that we had previously. The consequence of this is that traffic between Cloudflare and Webflow would be sent in plaintext.
- Our investigation was slowed by maintainers not having quick admin access to the Webflow account. We will look at transferring those rights to one of us.
