### ISSUE TITLE
Release 2022.10.2 (hotfix) 

### ISSUE THREAD

**Issue by mrocklin** [dask/community#284]
Everyone without Bokeh is currently getting failing clusters, as reported at https://github.com/dask/distributed/issues/7227 and https://github.com/dask/dask/issues/9609 and fixed in https://github.com/dask/distributed/pull/7230 by @oliverholworthy

I'm going to be pushing out a hotfix now.

**Comment by jrbourbeau** [comment]
+1 -- thanks for handling @mrocklin. Release procedures are here https://github.com/dask/dask/blob/main/docs/release-procedure.md. The only thing that's changed since the last time you've released is you need to be sure to update the `dask` / `distributed` version pinning since they are now tightly pinned (i.e. make sure `dask=2022.10.2` pins `distributed=2022.10.2` and vice versa). Here's an example of that happening in the release last Friday https://github.com/dask/dask/commit/67beb3ec71b55f3fc2f82b3b7aa6be20b06085a5 and https://github.com/dask/distributed/commit/1db2595266fadd9b9163f6802707bdcc53c71214

**Comment by potiuk** [comment]
Cool. Thanks for such quick response :)

**Comment by mrocklin** [comment]
Proceding with the release now

**Comment by mrocklin** [comment]
Pushed to PyPI

**Comment by potiuk** [comment]
Build is running for Airflow : https://github.com/apache/airflow/pull/27415

**Comment by potiuk** [comment]
And Mergeed! All tests with dask passed. Thanks for super quick reaction @mrocklin and the Dask team.

**Comment by mrocklin** [comment]
No worries.  My apologies for the confusion.

**Comment by charlesbluca** [comment]
Looks like conda-forge didn't automatically open PRs to bump to 2022.10.2, so opened them manually:

- https://github.com/conda-forge/dask-core-feedstock/pull/149
- https://github.com/conda-forge/distributed-feedstock/pull/228
- https://github.com/conda-forge/dask-feedstock/pull/202

cc @jakirkham in case you have any idea why this might be? My first guess was that the dependency metadata didn't change at all between releases

**Comment by jakirkham** [comment]
The bot that opens these PRs does so on a cron job. So it depends a bit on when the release happened and when the last cron job was run.

**Comment by jakirkham** [comment]
Anyways all of those packages are published as are the new Docker images ( https://github.com/dask/dask-docker/pull/258 ). Closing as completed. Though if I've missed something, please feel free to reopen.

Thanks all! 🙏

**Comment by jrbourbeau** [comment]
Thanks all!
