### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by mrocklin** [dask/community#291]
I've made a google group under the dask.org domain for a newsletter.  Folks can subscribe by sending an e-mail to newsletter+subscribe@dask.org .  

Apparently we've had a newsletter signup form on the new webpage for a while.  I'm going to go dump those addresses into that mailing list group and then advertise the demo day, the recent release, and the blogpost about task queuing (a biggish feature).  (this last blog is on the coiled blog, so this is somewhat self-serving.  I'd welcome anyone weighing in saying "eh, that seems odd" or "yup, makes sense" so that I'm not unilaterally promoting things).  

If folks want access this is all managed through google groups.  Members can't see each other or post to the list, only managers can do that.   Currently managers include myself, @jacobtomlinson , and @LilyMelnyk for admin reasons.  If other owners want access please let me know.  I do think that we should coordinate sending out messages though and not push lots of small things.  I'd like for this to be a low-volume list.

**Comment by mrocklin** [comment]
https://groups.google.com/a/dask.org/g/newsletter/c/YGXsPS-tFz4/m/EJsXW2-6EAAJ?utm_medium=email&utm_source=footer

**Comment by jrbourbeau** [comment]
> this last blog is on the coiled blog, so this is somewhat self-serving. I'd welcome anyone weighing in saying "eh, that seems odd" or "yup, makes sense" so that I'm not unilaterally promoting things

My sense this is okay if we're sending out Dask-related blog posts in the newsletter. This particular one is from Coiled, but I could easily see us wanting to send out a blog post from NVIDIA, Anaconda, @jacobtomlinson's personal blog, etc. Though I'd certainly welcome thoughts from non-Coiled folks like @jacobtomlinson

FWIW I've also asked @gjoseph92 to cross-post the queuing blog post on the Dask blog. We could link to that once it exists if folks prefer.

**Comment by mrocklin** [comment]
> FWIW I've also asked @gjoseph92 to cross-post the queuing blog post on the Dask blog. We could link to that once it exists if folks prefer

Marketing folks have trained me to be concerned about the SEO impacts of duplicating blogposts.  It might be wise to use a canonical link meta thing or whatever.

**Comment by mrocklin** [comment]
Initial draft (just a few minutes of writing, but I'm pretty ok with it)

<img width="447" alt="Screen Shot 2022-11-16 at 4 17 48 PM" src="https://user-images.githubusercontent.com/306380/202306453-b832f5bb-aac6-4f7d-8d48-382435d446bc.png">

**Comment by jrbourbeau** [comment]
Thanks for the heads up -- I'll reach out to @LilyMelnyk so we try to do the right thing from an SEO perspective. I still think we should cross-post on the Dask blog to cast a wider net for folks who may be interested in the content of that post.

**Comment by LilyMelnyk** [comment]
> > FWIW I've also asked @gjoseph92 to cross-post the queuing blog post on the Dask blog. We could link to that once it exists if folks prefer
> 
> Marketing folks have trained me to be concerned about the SEO impacts of duplicating blogposts. It might be wise to use a canonical link meta thing or whatever.

@mrocklin I've trained you well, young grasshopper. And I am here to echo the same.

**Comment by LilyMelnyk** [comment]
@jrbourbeau let's connect tomorrow and I can give a couple of options?

**Comment by ntabris** [comment]
Might be polite to link to Deepak's [website](https://cherian.net) or twitter?

**Comment by gjoseph92** [comment]
Less punchy but gets across more directly what kind of improvements we're talking about:

![image](https://user-images.githubusercontent.com/3309802/202315997-e03361e7-692b-4fb2-b6e3-ae4f0978e46d.png)

https://github.com/dask/distributed/discussions/7128#discussioncomment-4140076

**Comment by gjoseph92** [comment]
@LilyMelnyk @jrbourbeau another option for the dask blog could be to turn https://github.com/dask/distributed/discussions/7128 into a blog post. Basically "here's the FAQ on what changed, click this link to the coiled blog to read more detail about how it works"?

**Comment by mrocklin** [comment]
I'm going to keep the punchy language.  I've linked to Deepak.  Scheduled
to go out early tomorrow morning at 3am US Central time (mostly to make the
today/tomorrow distinction matter less for EU/US readers)

**Comment by jacobtomlinson** [comment]
I have no problems with the Dask newsletter promoting Coiled content provided it also promotes content from others, but I don't think there is any doubt about that. So the draft here gets a +1 from me.

I would argue that the wording should make it clear that any content that isn't on a Dask channel is "community content" rather than "official content". Community content would include content from Coiled, RAPIDS, etc. What I want to avoid is that folks interpret Coiled content as being the voice of Dask, this is challenging because Matt is the face of both Dask and Coiled and so we should think about this a little. I feel like the line is very blurry currently.

I wrote a long comment about this a while ago so I won't rehash that here https://github.com/dask/community/issues/259#issuecomment-1167263925. 

It would be nice to have a submission process for including things in the newsletter. Probably just an issue exactly like this one but with a longer timescale like 24 hours to give folks a chance to respond. There has been a 3-hour window between this issue being opened and the email being scheduled (in the middle of the night in Europe) so maybe just extend that a bit?

For example, I would've liked to propose https://developer.nvidia.com/blog/accelerating-etl-on-kubeflow-with-rapids/ which is a blog post about using RAPIDS on Kubeflow that heavily uses Dask. I'm also open to pushback on that post being too far on the corporate content scale, but my response would be that we should just label it as such.

**Comment by mrocklin** [comment]
Yup.  Agreed on the timescale.  I pushed this out early in order to see the impact on Demo Day.  A longer time period makes sense I think.

Demo day creates a nice cadence. It forces me to collect things every month at least.  I wouldn't mind doing this twice a month (maybe also with the community meeting as the other forcing function).

**Comment by mrocklin** [comment]
OK, this is up and running.  I'm going to close this issue for now.  I might try to softly push this in a few channels and see what happens to the subscriber count.
