### ISSUE TITLE
Discourse

### ISSUE THREAD

**Issue by mrocklin** [dask/community#46]
I found myself this morning in a call with a surprising number of beamline scientists (15 or so?)

It was a great conversation, and at the end said "how can we communicate together in the future?"  The consensus from that meeting was that a Dask Discourse with a beamline tag/group would be useful (they preferred this over other mechanisms, like an e-mail list, slack, or an existing community structure)

This has happened often enough that I'm now somewhat inclined to make such a discourse.  This has come up previously and hasn't always been met with full enthusiasm, so I figured I'd make space to discuss this here.

**Comment by jakirkham** [comment]
I thought this was something NumFOCUS was working on for all sponsored projects (though haven't checked in on that). Is that still true?

**Comment by mrocklin** [comment]
I don't know, but in either event I wouldn't want to wait for them

**Comment by jakirkham** [comment]
Do you mind checking with NumFOCUS first? It would be a bit silly to setup a second Discourse if one already exists. Not to mention a bit of extra maintenance effort to keep up with.

**Comment by mrocklin** [comment]
Sounds great

**Comment by mrocklin** [comment]
Oh I see, after reading your message again it sounds like you're expecting me to engage with NumFOCUS here.  Sure, I'll send an e-mail.

**Comment by jakirkham** [comment]
Thanks Matt 🙂

**Comment by mrocklin** [comment]
Not much has happened here.  I have a waiting community and I think that there is loss in waiting further.  I'm inclined to move forward.  If someone has bandwidth to push harder on NumFOCUS that would be great, but it doesn't seem like that's the case.

**Comment by jakirkham** [comment]
On the email thread it sounded like they had something, but then the ball was dropped regarding sharing details. I prodded it again. If we don’t hear something by end of week, I’d be fine doing whatever here.

**Comment by jakirkham** [comment]
Looks like Andy responded. I'm not entirely sure how you want this setup. If you could please engage with him, that would be helpful 🙂

**Comment by mrocklin** [comment]
For others, response from Andy

> I created this group at the request of the pandas team, they decided it wasn't useful for multi repo discuss channels. I'm all ears to how to configure it in a way that makes sense.

From @jakirkham 

> I'm not entirely sure how you want this setup. If you could please engage with him, that would be helpful 

I'm not sure I understand.  I don't want to go through NumFOCUS.  I just want to do this myself.  I engaged NumFOCUS at your request and it sounds like they're not especially set up and keen to work on this.  At this point we're two weeks delayed and so I'm inclined to not lose any more time.

If you feel strongly that we should go through NumFOCUS rather than having me do it personally that's ok, but I would prefer it if you would engage directly, rather than have me drive something that I don't actually want to occur.

**Comment by jakirkham** [comment]
Was only interested in making sure we are aligned with larger community efforts. It sounds like this is not relevant. Please proceed however you see fit 🙂

**Comment by mrocklin** [comment]
OK, we're up here: https://dask.discourse.group/

We may want to seed this with users and categories.  I haven't yet given this much thought, but I'll try to think on it in the near future.  In the meantime, people might want to check it out and say hi.

**Comment by mrocklin** [comment]
I figure that we phase rolling this out in stages.  We probably want to model good behavior before we advertise widely.  We probably also want to figure out what good behavior is before we can model it :)

**Comment by lesteve** [comment]
So I guess now that the Discourse forum exists, what do we make of it?

1. do we just try to use it and see what happens? I guess a good start would be to fill out [Introductions](https://dask.discourse.group/c/introductions/5) for a few of us
2. do we try to define some broad categories. For now, we have "Dataframes", "Delayed-Futures", "Arrays", "GPUs". Are we happy with that (I need to read a bit more about Discourse [categories vs tags](https://blog.discourse.org/2017/10/its-time-we-talked-about-tags/))? Should we add "HPC" and "Cloud"? Should we add "Machine Learning"? Should we thing a bit more about Categories vs Tags 
3. it seems like @mrocklin was saying that having a scientific field orientation could be useful (beamline scientists was the motivation for creating this Discourse forum). Maybe it is simple as adding a "beamline" tag rather than creating a category.
4. do we try to brainstorm what kind of content goes to Discourse vs say StackOverflow or Discourse vs Gitter or even harder Dask Discourse vs Pangeo Discourse ?

Personally I would be in favour of 1., 2., 3. soonish and maybe wait a bit to discuss 4. because it feels like a can of worms. I also think I am more likely to answer questions on Discourse than StackOverflow or Gitter, I don't know really why ...

Full disclosure : I am in no way an advanced Discourse user, I have mostly used them as weekly automatic email for summary activity and I decide whether I want to read some of the posts (mostly Jupyter and Pangeo).

Opinions on this would be more than welcome!

Maybe @rabernat and @jhamman can share some insights of running and using the Pangeo Discourse? Maybe some people close to the Jupyter (not sure who to ping at the intersection of Jupyter and Dask) project can also chime in?

**Comment by jakirkham** [comment]
All of those seem like great ideas @lesteve! 😄

**Comment by mrocklin** [comment]
@lesteve I think that this whole thing is an experiment.  The only wrong answer is for us not to try something :)  Probably it will be wrong and we'll do something else afterwards.  Broadly, I think that there are three stages to this:

1.  Set up some basic structure.  This helps new people arrive and know what is going on.  Maybe we need to seed this structure with some content of our own?
2.  Start inviting people to participate in it, maybe we start by redirecting gitter conversation into discourse, or moving some github issues into discourse, especially if they are about solving a domain specific problem, rather than a bug in Dask.
3.  Track discourse to make sure that there is some response to people early on
4.  Assess the situation as a group, and make some design changes to the structure that we decided on in 1

I'm happy to help provide some time on this, but it's probably not a good idea for me to lead it.  In general I share your concern that we don't really know what is best here, but I think that that is ok at this stage.  We will figure things out I think.

**Comment by lesteve** [comment]
I am happy to put some time/energy into this initiative and see what happens. If that qualifies as "leading" I am fine with that too :wink:.

So here is what I did:
- I answered a few posts that were already there without answers and pinged a few persons that may be able to help
- I wrote an introduction about myself [here](https://dask.discourse.group/c/introductions/50) and invite others to do it as well if they wish
- and a few other minor things

Maybe if I was given necessary permissions I could try to edit the category description that seems like a templates right now, for example https://dask.discourse.group/t/about-the-delayed-futures-category/22. Or you can do it as well if prefer no worries.

**Comment by mrocklin** [comment]
> Maybe if I was given necessary permissions I could try to edit the
category description that seems like a templates right now, for example
https://dask.discourse.group/t/about-the-delayed-futures-category/22. Or
you can do it as well if prefer no worries.
Done

**Comment by lesteve** [comment]
I added some minimal content to the Discourse categories description.

Maybe people can write a few words about themselves in the "Introductions" category. Here is a pre-filled topic link that should directly allow you to compose your introduction post:
[click here to write your introduction](https://dask.discourse.group/new-topic?title=Put%20your%20name%20here&body=A%20few%20words%20about%20yourself&category=introductions)

**Comment by sterlinm** [comment]
Is the Dask Discourse gone?

**Comment by martindurant** [comment]
Conversation is now on slack, see https://github.com/dask/community/issues/118

**Comment by jsignell** [comment]
Maybe it's time to close this issue :)
