### ISSUE TITLE
Dask Summit later this year

### ISSUE THREAD

**Issue by hugobowne** [dask/community#78]
hi all,

I had a great time reading the dask-summit blogpost.

I was wondering if we wanted to do this again. One idea could be to make it more Dask user-focused?

I'd love for this to be a topic for next month's developer meeting and I'd happily add it to the agenda. 

Unfortunately due to time zones (I'm in Australia) I won't be able to make the meeting, but I'd be happy and excited to help generally make this happen. I thought to also note that I work with @mrocklin at Coiled.

**Comment by jakirkham** [comment]
This could be interesting. Though travel (certainly in the US) is a bit frought atm. Would the idea be to make this virtual then?

**Comment by hugobowne** [comment]
Oh yeah! My suggestion would be for a virtual summit. 

Could call it a Dask Distributed Summit? jk sorry!

**Comment by jakirkham** [comment]
Sounds great 😀

**Comment by jsignell** [comment]
I really like the idea of a Dask Distributed Summit and I think that is 100% what it should be called. 

My employer (Saturn Cloud) would also be very excited to sponsor and/or help coordinate an event like this. I imagine Prefect might also be interested (cc @jcrist).

**Comment by quasiben** [comment]
I'd be in favor of this as well

**Comment by kkraus14** [comment]
cc @datametrician @mikebeaumont for visibility

**Comment by jsignell** [comment]
We discussed this idea at the general meeting just now and people seem to think that it might be interesting, but we'd want to be very thoughtful about how it is structured and what we are trying to achieve. In particular, we want to think about: 

### Audience
We'd want to be clear about the intended audience: novice, intermediate, power user, dev. People seem most interested in targeting higher-level users. The novice users are likely well served by existing tutorials #57 and general conference talks (PyData, SciPy). Higher-level users on the other hand might be interested in meeting others with their problems and creating working groups.

### Goals
One goal would be to get feedback from users on what is important to them. An additional goal might be encouraging users to interact more with each other to solve their problems. We probably want to solidify our goals before doing any planning. 

### Async vs Sync
At SciPy they pre-recorded normal talks and did QA, tutorials, and lightning talks synchronously. The sense was that this didn't work great for tutorials. Synchronous sprints worked pretty well, but need to have more direction than in-person ones. 

### Types of events
We want to avoid webinar vibes and find a clever way to get people to interact. Maybe this looks more like lightning talks or discussions in working groups ( like SciPy "Birds of a Feather" sessions). 

### Cost
This should not be free. People are less flaky and more likely to have real interest if they have to pay something. We can make it cheap and provide scholarships to mitigate this. 

### Alternate Proposals
Maybe instead of one event we should periodically release short videos and host synchronous QA sessions. This would complement the ongoing tutorial schedule, but the talks could be a bit more advanced: "dask for bio-medical imaging" or the like. We could have corresponding user-groups with some established means of interaction (maybe discourse) and/or regular meetings. Note this is similar to what Pangeo does. 

Full conversation notes at: https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit#

**Comment by jsignell** [comment]
We have been thinking about this idea again and it's been sounding pretty appealing. Especially given how well a conference seems to be working out for Ray. Here is a tentative proposal:

### Why
- Help novices get more exposure into what Dask can do
- Give high-level users a space/time to talk with each other and get help

### Who
There could be different types of events targetting different level users. Something like talks/tutorials targetting novice and intermediate users, working groups for higher-level users.

### How
Since it'll be remote, talks could be pre-recorded and the discussion can be synchronous. Then we can have a slack where people can chat.
I think there should also be a strong focus on providing an unconference space. That might look like a conference hall in gather.town with the areas labeled and a slack.

### When
There should be a specific 2 day time period when this conference is. Maybe early December?

**Comment by martindurant** [comment]
I would mildly warn against organising anything in the last two months of a year, people tend to get busy with other things. Granted, this is hardly a typical year, but still worth mentioning.

**Comment by hhuuggoo** [comment]
Spoke briefly to @pzwang and @teoliphant about Anaconda and Quansight being involved (they were +1)

cc @quasiben, @datametrician

**Comment by datametrician** [comment]
I love Dask Distributed Summit. Down to support!

**Comment by mrocklin** [comment]
I agree with @martindurant that trying to do something in the next couple of months seems ambitious.  I would aim for January/February of next year, which puts it in-line with what happened last year.

@datametrician can you swing some of Jake Schmitt's time?  He was pretty awesome in running this thing last year.

I recommend that we discuss this at the monthly meeting next week.

**Comment by jrschmitt** [comment]
CC: @mikebeaumont

**Comment by roaramburu** [comment]
BSQL crew also down to both support and participate.

cc @williamBlazing @felipeblazing

**Comment by datametrician** [comment]
@mrocklin don't you have a company :P but yes I'll see what I can do regarding Jake's time.

**Comment by mrocklin** [comment]
I do, and I imagine that we'll have some role here whether as a lead or in support.

However, Jake was pretty awesome last time.  I think that, if he is interested, a Dask conference would be better for having Jake's engagement.

`<kidding, mostly>` 
The best arrangement, in my mind, is that you fire Jake, we hire him, and then Jake runs the conference :) 
`</kidding, mostly>`

**Comment by jrschmitt** [comment]
No need to fire me, I'm in. 

We're starting way earlier than we did last year, so we're off to a good start. I'll have some thoughts and questions documented for the Dask Community meeting next Thursday, so we can get this thing moving. 

Is there a particular public folder I should put this document in?

**Comment by mrocklin** [comment]
I've made a "Conference 2021" folder in the Dask shared drive and shared it with you.

> No need to fire me, I'm in.

Darn.

**Comment by mrocklin** [comment]
There is also here (which is more public, which is nicer)

And also the public agenda for the meeting  https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit?usp=sharing

**Comment by jrschmitt** [comment]
Awesome, just got the folder. I'll put details there, then summarize for the agenda.

**Comment by jrschmitt** [comment]
@mmccarty @gforsyth want to get the band back together and collaborate organizing this again?

**Comment by jrschmitt** [comment]
Put some questions on paper that we should answer as a group on Thursday. I know some of these have been touched on in this thread, but I can't find definitive answers here or in other cited documentation.

If we can answer these Thursday, a planning committee has enough to start moving into detailed planning.

Link: https://docs.google.com/document/d/1WWTpcL7xWMORlN2DZWt9ka36VrBiMgN-swtfqfbwknw/edit

**Comment by mmccarty** [comment]
+1 for a Dask Distributed Workshop 🔥

**Comment by hugobowne** [comment]
There are a lot of big energies in this thread: I like it!

As I'm in Australia, I can't make the meeting.

However, as Head of Marketing & Evangelism at Coiled, I would be > excited about supporting with time and expertise, both from myself and my team (I'd need to run this by my boss when he's in a good mood but that should be fine :P).

I've been connecting a lot with the Dask user community this year, through our Science Thursday initiatives, among other things, and I'd be happy to leverage the community building we've been doing here for this summit, in whatever way it would be most helpful.

I'd also be down for working with @jrschmitt on the Summit (I'll take any reason to chat with Jake!).

Of course, we'd be happy to discuss sponsorship etc... but the more exciting conversation for me (not mutually exclusive) is how we can get involved to make the best darn Dask Distributed Summit ever.

**Comment by mrocklin** [comment]
> I'd need to run this by my boss when he's in a good mood but that should be fine

With my Coiled hat on I'm all for this.

With my Community hat on I encourage us all to be mindful here.

I want Dask to maintain a strong community feel.  Any company that organizes a Dask conference is likely to be perceived as the Dask authority.  This is extremely valuable today, and marketing departments from startups are likely to present themselves in order to get it.  I encourage the community to be aware of this if it chooses to grant that mantle.

This can be done well or poorly.  I think that the Spark/AI Summit by Databricks is a negative example, while SciPy supported by Enthought is a positive example I think (SciPy feels community led, and not "owned" by Enthought).  PyCon is an entirely different model, where no corporation can claim to have organized the conference, and instead it is entirely community run.  

Personally, I try very hard to separate my coiled interests from my Dask activities and I see most other people in the community doing this as well today.  My guess is that we'll easily find an arrangement and a set of marketing policies that everyone is comfortable with this time around, but I do want everyone to start off in a slightly uncomfortable state, just so that this balance and corporate behavior is in mind.  This time next year the landscape may look different, and this feels like a useful muscle for us to begin to exercise.

**Comment by jrschmitt** [comment]
@jsignell @mrocklin @mmccarty @hugobowne 

When should we meet to start officially planning? Once we meet, let's close this ticket then move into other mechanisms for collaboration.

**Comment by mrocklin** [comment]
I'm around any time.  Timezones are a bit tricky with Hugo, but I think
it'd be good for him to be present at least for the first meeting.  Are
east-coast folks available later some afternoon next week?

**Comment by jsignell** [comment]
Yeah Monday, Tuesday or Wednesday afternoon are good for me.

**Comment by jrschmitt** [comment]
Tuesday afternoon next week (10 NOV) would be ideal.

**Comment by hugobowne** [comment]
I'm currently free from 230pm to 330pm PT Nov 10, at 4pm for 30 minutes, and then from 5pm onwards. I'm also free on Nov 11 from 3pm PT. Feel free to send an invite!

**Comment by mmccarty** [comment]
I should be able to make most times work Thursday afternoon.

**Comment by pzwang** [comment]
Should there perhaps be an email thread with a Doodle or something?

**Comment by mrocklin** [comment]
This was taken off to an e-mail thread.  If anyone is interested please get
in touch and I'll cc you.

**Comment by mrocklin** [comment]
Ah, things were scheduled for Tuesday 2020-11-10 at 4:30pm US Central time.

**Comment by jrschmitt** [comment]
After kicking off planning last night and structuring a regularly meeting cadence, I think this issue can be closed. Thoughts?

**Comment by jsignell** [comment]
Yep for anyone interested we are meeting every Tuesday at 4:30 central in the regular whereby room.

**Comment by martindurant** [comment]
Please add me to the organisers, if you don't mind - and sorry for being late to the party.

**Comment by mrocklin** [comment]
Awesome.  It would be great to have representation from Anaconda.
